FILEPATH = "../data/GCA_004026985.1_MyoMyo_v1_BIUU_genomic.fna"
CONFIG_FILEPATH = "config/config.json"
NEWLINE = "\n"
TEMP_FASTA_FILE = "/tmp/temp.fasta"
TEMP_BLASTN_OUTPUT = "/tmp/blastn.json"
LTR_OUTFILE = "ltr_candidates.fasta"
LTR_LOWER = 200
LTR_UPPER = 600
ENV_UPPER = 3000 + (LTR_UPPER * 2)
